# Created by: Marcin Cieslak <saper@saper.info>
# $FreeBSD$

PORTNAME=	node-sass
PORTVERSION=	2.0.1
CATEGORIES=	www

MAINTAINER=	saper@saper.info
COMMENT=	Node bindings for the C/C++ implementation of a Sass compiler

LICENSE=	MIT

GH_ACCOUNT=	sass
GH_COMMIT=	5bff1c7
GH_TAGNAME=	${PORTVERSION}

INSTALL_TARGET=	install-strip

USES=		compiler:c++0x
USE_GITHUB=	yes

.include <bsd.port.mk>
