# Created by: saper@saper.info
# $FreeBSD$

PORTNAME=	webencodings
PORTVERSION=	0.5.1
CATEGORIES=	converters python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	saper@saper.info
COMMENT=	Python implementation of the WHATWG Encoding standard

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
